# Generated by Django 2.1.4 on 2018-12-06 18:06

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('image', models.ImageField(null=True, upload_to=expenses.models.upload_image_path)),
                ('date', models.DateField()),
            ],
        ),
    ]
