# Generated by Django 2.1.4 on 2018-12-07 07:32

from django.db import migrations, models
import expenses.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=expenses.models.upload_image_path),
        ),
    ]
